shtrixkod/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.record_create, name="record_create"),
    path("records/<int:record_id>/add_issue_date/", views.record_add_issue_date, name="record_add_issue"),
    path("records/<int:record_id>/edit/", views.record_edit, name="record_edit"),
    path("records/<int:record_id>/delete/", views.record_delete, name="record_delete")
]

shtrixkod/shtrixkod/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("posts.urls", namespace="index")),
    path("admin-skod/", admin.site.urls),
]

shtrixkod/posts/models.py
from django.db import models

LENGTH_TEXT_POST = 15


class Record(models.Model):
    """Модель записи."""

    name = models.TextField(
        blank=False,
        verbose_name="Наименование",
        help_text="Введите наименование",
        max_length=150
    )
    marking = models.CharField(
        blank=False,
        verbose_name="Маркировка",
        help_text="Введите маркировку",
        max_length=30
    )
    amount = models.IntegerField(
        blank=False,
        verbose_name="Количество мест",
        help_text="Введите количество мест"
    )
    weight = models.FloatField(
        blank=False,
        verbose_name="Вес",
        help_text="Введите вес в килограммах"
    )
    volume = models.FloatField(
        blank=False,
        verbose_name="Объем",
        help_text="Введите объем в м³"
    )
    add_date = models.DateField(
        blank=False,
        auto_now_add=False,
        verbose_name="Дата поступления на склад"
    )
    issue_date = models.DateField(
        blank=True, null=True,
        auto_now_add=False,
        verbose_name="Дата выдачи"
    )
    recipient = models.TextField(
        blank=False,
        verbose_name="Заказчик",
        help_text="Введите имя заказчика",
        max_length=150
    )
    comment = models.TextField(
        blank=True,
        verbose_name="Комментарий",
        help_text="Введите комментарий",
        max_length=150
    )

    class Meta:
        verbose_name_plural = "Записи"
        verbose_name = "Запись"
        ordering = ["issue_date", "-add_date"]

    def __str__(self):
        name = self.name
        first_fifteen_chars = name[:LENGTH_TEXT_POST]
        return first_fifteen_chars

shtrixkod/posts/forms.py
from django import forms

from .models import Record


class DateInput(forms.DateInput):
    input_type = "date"


class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = (
            "name",
            "marking",
            "amount",
            "weight",
            "volume",
            "add_date",
            "recipient",
            "comment"
        )

        widgets = {
            "name": forms.Textarea(attrs={'rows': 3}),
            "add_date": DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'date'
                    }
            ),
            "recipient": forms.Textarea(attrs={'rows': 3}),
            "comment": forms.Textarea(attrs={'rows': 3})
        }


class RecordFormIssueDate(forms.ModelForm):
    class Meta:
        model = Record
        fields = (
            "issue_date",
        )

        widgets = {
            "issue_date": DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'date'
                    }
            ),
        }

shtrixkod/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q

from .models import Record
from .forms import RecordForm, RecordFormIssueDate


def index(request):
    """Главна страница сайта."""
    template = "posts/index.html"

    options_data = request.GET

    record_list = Record.objects.exclude(~Q(issue_date=None))
    if "f" in options_data.keys() and options_data["f"] != "":
        record_list = Record.objects.all()
    if "o" in options_data.keys() and options_data["o"] != "":
        options = options_data["o"].split(",")
        options = [x for x in options if x != ""]
        record_list = record_list.order_by(*options).all()

    page_obj = paginator(request, record_list)
    context = {
        "page_obj": page_obj,
        "querydict": options_data
    }

    is_info_msg = request.session.get("is_info_message")
    if is_info_msg:
        context["is_info_message"] = is_info_msg
        request.session.pop("is_info_message", None)

    return render(request, template, context)


def record_create(request):
    """Страница создания новой записи."""
    template = "posts/create_post.html"
    form = RecordForm(files=request.FILES or None)
    context = {"form": form}
    if request.method == "POST":
        form = RecordForm(request.POST or None, files=request.FILES or None)
        if form.is_valid():
            record = form.save(commit=False)
            record.save()
            request.session["is_info_message"] = "Запись успешно создана"
            return redirect("index:index")
        return render(request, template, context)
    return render(request, template, context)


def record_add_issue_date(request, record_id):
    """Страница добавления даты выдачи."""
    record = get_object_or_404(Record, id=record_id)
    template = "posts/create_post.html"
    form = RecordFormIssueDate(files=request.FILES or None, instance=record)
    context = {
        "form": form,
        "is_add_issue": True
    }
    if request.method == "POST":
        form = RecordFormIssueDate(
            request.POST or None, files=request.FILES or None, instance=record
        )
        if form.is_valid():
            record.save()
            request.session["is_info_message"] = "Дата выдачи успешно добавлена"
            return redirect("index:index")
        return render(request, template, context)
    return render(request, template, context)


def record_edit(request, record_id):
    """Страница редактирования записи."""
    record = get_object_or_404(Record, id=record_id)
    template = "posts/create_post.html"
    form = RecordForm(files=request.FILES or None, instance=record)
    context = {
        "form": form,
        "record_id": record_id,
        "is_edit": True
    }
    if request.method == "POST":
        form = RecordForm(
            request.POST or None, files=request.FILES or None, instance=record
        )
        if form.is_valid():
            form.save()
            request.session["is_info_message"] = "Запись успешно отредактирована"
            return redirect("index:index")
    return render(
        request,
        template,
        context,
    )


def record_delete(request, record_id):
    """Удаление записи."""
    record = get_object_or_404(Record, id=record_id)
    record.delete()
    request.session["is_info_message"] = "Запись успешно удалена"
    return redirect("index:index")


def paginator(request, post_list):
    paginator = Paginator(post_list, 25)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return page_obj

shtrixkod/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/fav/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'img/fav/safari-pinned-tab.svg' %}" color="#182533">
    <meta name="msapplication-TileColor" content="#182533">
    <meta name="theme-color" content="#182533">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Oswald:wght@200..700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" integrity="sha384-4LISF5TTJX/fLmGSxO53rV4miRxdg84mZsxmO8Rx5jGtp/LbrixFETvWa5a6sESd" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    
    <title>
      {% block title %}
        Главная страница
      {% endblock %}
    </title>

  </head>

  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>   

    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>

    <footer class="footer mt-auto font-small text-secondary py-2">
      {% include 'includes/footer.html' %}
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" crossorigin="anonymous"></script>

    <script>
        toastr.options.positionClass = "toast-top-center"

        {% if is_info_message %}
            toastr.success("{{ is_info_message }}")
        {% endif %}
    </script>

  </body>
</html>

shtrixkod/templates/includes/footer.html
<div class="footer-copyright text-center py-3">
    <font size="1">«Штрих-Код» v 1.0</font><br>
    <font size="2">© {{ year }} Copyright <a href="https://t.me/codered_dev" target="_blank" class="text-secondary">«Code;Red»</a></font>
</div>  

shtrixkod/templates/includes/form.html
{% load user_filters %}
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}            
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}
<form method="post" enctype="multipart/form-data" {% if action_url %} action="{% url action_url %}" {% endif %}>
  {% csrf_token %}
  {% for field in form %}<div class="form-group row my-3"
    {% if field.field.required %} 
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}>
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
    <div>
    {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}

shtrixkod/templates/includes/header.html
{% load static %}
{% load user_filters %}
<nav class="navbar navbar-expand-md navbar-dark">
  <div class="container">
    <a class="navbar-brand" style="font-size: 25px;" href="{% url 'index:index' %}">
      <img src="{% static 'img/logo.png' %}" width="32" height="32" class="d-inline-block align-top" alt="">
      «ШТРИХ-КОД» <font class="align-top" size="2">v 1.0</font>
    </a>
    <div class="collapse navbar-collapse mr-auto" id="navbarText">
      {% with request.get_full_path as path %}
        <ul class="navbar-nav ms-auto mb-2 mb-md-0 text-center">
          <li class="nav-item">
            <a class="nav-link {% if path == "/" or path|startswith:"/?o=" or path|startswith:"/?f=" %}active{% endif %}" aria-current="page" href="{% url 'index:index' %}">
              ПРОСМОТР
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              ОТЧЁТЫ
            </a>
          </li>
      {% endwith %}
          <li class="nav-item">
            <a class="help-icon" data-bs-toggle="modal" data-bs-target="#exampleModal">
                <img src="{% static 'img/help-button.png' %}" class="mt-1" alt="Поддержка" width="35" height="35">
            </a>
          </li>
        </ul>
    </div>
  </div>
</nav>

{% include 'includes/modal_help.html' %}

shtrixkod/templates/includes/modal_help.html
<!-- Модальное окно -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content modal-style">
            <div class="modal-header">
                <h4 class="modal-title aqum-font" id="exampleModalLabel">Техническая поддержка</h4>
            </div>
            <div class="modal-body">
                • При возникновении проблем и вопросов технического характера, Вы можете обратиться в поддержку через Телеграм <a href="https://t.me/B776YC" target="_blank" class="link-primary"><i class="ri-telegram-fill"></i> @B776YC</a>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary aqum-font" data-bs-dismiss="modal">Закрыть</button>
                <a href="https://t.me/B776YC" target="_blank" type="button" class="btn btn-primary aqum-font" style="background-color: #2d6eb4;">Перейти в Телеграм</a>
            </div>
        </div>
    </div>
</div>

shtrixkod/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %} 
    Редактирование записи 
  {% elif is_add_issue %}
    Добавление даты выдачи
  {% else %} 
    Новая запись 
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-5 p-3">
      <div class="card">
        <div class="card-header">
          {% if is_edit %} 
            Редактирование записи
          {% elif is_add_issue %}
            Добавление даты выдачи
          {% else %} 
            Добавление записи 
          {% endif %}
        </div>
        <div class="card-body">
          {% include 'includes/form.html' %}
          <div class="row">
            <div class="col offset-md-4">
              <button type="submit" class="btn btn-primary btn-style">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %} 
              </button>
              <a type="button" class="btn btn-outline-secondary" href="{% url 'posts:index' %}">Отменить</a>
            </div>
            <div class="col d-flex justify-content-end">
              {% if is_edit %}
                <a class="btn btn-outline-danger" href="{% url 'posts:record_delete' record_id %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                    <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
                  </svg>
                </a>
              {% endif %} 
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div>
{% endblock %}

shtrixkod/templates/posts/includes/modal_post.html
<!-- Модальное окно -->
<div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content modal-style">
            <div class="modal-header">
                <h4 class="modal-title aqum-font" id="exampleModalLabel">Дата выдачи</h4>
            </div>
            <div class="modal-body">
                {% include 'includes/form.html' %}
            </div>
            <div class="modal-footer justify-content-center">
                <button type="button" class="btn btn-outline-secondary aqum-font" data-bs-dismiss="modal">Закрыть</button>
                <button type="submit" class="btn btn-primary btn-style" href="{% url 'index:record_create' %}">Добавить</button>
            </div>
        </div>
    </div>
</div>
{% comment %} 
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %} 
    Редактирование записи 
  {% else %} 
    Новая запись 
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %} 
            Редактирование записи 
          {% else %} 
            Добавление записи 
          {% endif %}
        </div>
        <div class="card-body">
          {% include 'includes/form.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-outline-dark">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %} 
            </button>
          </div>
        </div>
      </div>
    </div> 
  </div>
{% endblock %} {% endcomment %}

shtrixkod/templates/posts/includes/table.html
{% load user_filters %}
<div class="table-responsive table-scroll" style="overflow: auto; height: 625px !important;">
    <table class="table table-bordered table-striped">
        <thead>
            <tr class="text-center">
                {% comment %} <th scope="col">№</th> {% endcomment %}
                <th scope="col">
                    <a class="link-light" href="?o={% if '-name' in querydict.o %}name,{{ querydict.o|checkoption:"-name" }}{% else %}-name,{{ querydict.o|checkoption:"name" }}{% endif %}">
                        Наименование
                    </a>

                    {% if '-name' in querydict.o %}
                    ▼
                    {% elif 'name' in querydict.o %}
                    ▲
                    {% endif %}
                    
                    {% if '-name' in querydict.o or 'name' in querydict.o %}
                      <a class="link-light" style="text-decoration: none;" href="?o={% if '-name' in querydict.o %}{{ querydict.o|checkoption:"-name" }}{% else %}{{ querydict.o|checkoption:"name" }}{% endif %}">
                        <small>  —</small>
                      </a>
                    {% endif %}
                </th>
                <th scope="col">
                  <a class="link-light" href="?o={% if '-marking' in querydict.o %}marking,{{ querydict.o|checkoption:"-marking" }}{% else %}-marking,{{ querydict.o|checkoption:"marking" }}{% endif %}">
                       Маркировка
                  </a> 

                  {% if '-marking' in querydict.o %}
                  ▼
                  {% elif 'marking' in querydict.o %}
                  ▲
                  {% endif %}
                  
                  {% if '-marking' in querydict.o or 'marking' in querydict.o %}
                    <a class="link-light" style="text-decoration: none;" href="?o={% if '-marking' in querydict.o %}{{ querydict.o|checkoption:"-marking" }}{% else %}{{ querydict.o|checkoption:"marking" }}{% endif %}">
                      <small>  —</small>
                    </a>
                  {% endif %}
              </th>
              <th>
                <a class="link-light" href="?o={% if '-amount' in querydict.o %}amount,{{ querydict.o|checkoption:"-amount" }}{% else %}-amount,{{ querydict.o|checkoption:"amount" }}{% endif %}">
                  Количество
                </a> 

                {% if '-amount' in querydict.o %}
                ▼
                {% elif 'amount' in querydict.o %}
                ▲
                {% endif %}
                
                {% if '-amount' in querydict.o or 'amount' in querydict.o %}
                  <a class="link-light" style="text-decoration: none;" href="?o={% if '-amount' in querydict.o %}{{ querydict.o|checkoption:"-amount" }}{% else %}{{ querydict.o|checkoption:"amount" }}{% endif %}">
                    <small>  —</small>
                  </a>
                {% endif %}
              </th>
              <th>
                <a class="link-light" href="?o={% if '-weight' in querydict.o %}weight,{{ querydict.o|checkoption:"-weight" }}{% else %}-weight,{{ querydict.o|checkoption:"weight" }}{% endif %}">
                  Вес
                </a> 

                {% if '-weight' in querydict.o %}
                ▼
                {% elif 'weight' in querydict.o %}
                ▲
                {% endif %}
                
                {% if '-weight' in querydict.o or 'weight' in querydict.o %}
                  <a class="link-light" style="text-decoration: none;" href="?o={% if '-weight' in querydict.o %}{{ querydict.o|checkoption:"-weight" }}{% else %}{{ querydict.o|checkoption:"weight" }}{% endif %}">
                    <small>  —</small>
                  </a>
                {% endif %}
              </th>
              <th>
                <a class="link-light" href="?o={% if '-volume' in querydict.o %}volume,{{ querydict.o|checkoption:"-volume" }}{% else %}-volume,{{ querydict.o|checkoption:"volume" }}{% endif %}">
                  Объем
                </a> 

                {% if '-volume' in querydict.o %}
                ▼
                {% elif 'volume' in querydict.o %}
                ▲
                {% endif %}
                
                {% if '-volume' in querydict.o or 'volume' in querydict.o %}
                  <a class="link-light" style="text-decoration: none;" href="?o={% if '-volume' in querydict.o %}{{ querydict.o|checkoption:"-volume" }}{% else %}{{ querydict.o|checkoption:"volume" }}{% endif %}">
                    <small>  —</small>
                  </a>
                {% endif %}
              </th>
              <th scope="col">
                  <a class="link-light" href="?o={% if '-add_date' in querydict.o %}add_date,{{ querydict.o|checkoption:"-add_date" }}{% else %}-add_date,{{ querydict.o|checkoption:"add_date" }}{% endif %}">
                      Дата приёма
                  </a> 

                  {% if '-add_date' in querydict.o %}
                  ▼
                  {% elif 'add_date' in querydict.o %}
                  ▲
                  {% endif %}
                  
                  {% if '-add_date' in querydict.o or 'add_date' in querydict.o %}
                    <a class="link-light" style="text-decoration: none;" href="?o={% if '-add_date' in querydict.o %}{{ querydict.o|checkoption:"-add_date" }}{% else %}{{ querydict.o|checkoption:"add_date" }}{% endif %}">
                      <small>  —</small>
                    </a>
                  {% endif %}
              </th>
              <th scope="col">Платное хранение с</th>
              <th scope="col">
                <a class="link-light" href="?o={% if '-issue_date' in querydict.o %}issue_date,{{ querydict.o|checkoption:"-issue_date" }}{% else %}-issue_date,{{ querydict.o|checkoption:"issue_date" }}{% endif %}">
                  Дата выдачи
                </a> 

                {% if '-issue_date' in querydict.o %}
                ▼
                {% elif 'issue_date' in querydict.o %}
                ▲
                {% endif %}
                
                {% if '-issue_date' in querydict.o or 'issue_date' in querydict.o %}
                  <a class="link-light" style="text-decoration: none;" href="?o={% if '-issue_date' in querydict.o %}{{ querydict.o|checkoption:"-issue_date" }}{% else %}{{ querydict.o|checkoption:"issue_date" }}{% endif %}">
                    <small>  —</small>
                  </a>
                {% endif %}
              </th>
              <th scope="col">Заказчик</th>
              <th scope="col">Комментарий</th>
              <th scope="col">🛠</th>
            </tr>
        </thead>

        <tbody id="table_info">
            {% for record in page_obj %}
                <tr>
                    {% comment %} <td><b>{{ record.pk }}</b></td> {% endcomment %}
                    <td>{{ record.name }}</td>
                    <td class="one-string">{{ record.marking  }}</td>
                    <td class="one-string">{{ record.amount  }} <small class="text-secondary">шт.</small></td>
                    <td class="one-string">{{ record.weight  }} <small class="text-secondary">кг.</small></td>
                    <td class="one-string">{{ record.volume  }} <small class="text-secondary">м³</small></td>
                    <td class="one-string">{{ record.add_date|date:"d.m.Y"  }}</td>
                    <td style="color: {{ record.add_date|paidstorage|checkdate:record.issue_date }};">
                      {{ record.add_date|paidstorage|date:"d.m.Y" }}
                      <small class="text-secondary">
                        {% if record.add_date|paidstoragesum %}
                          {{ record.volume|getpaidstoragesum:record.add_date }} руб.
                        {% else %}
                          0 руб.
                        {% endif %}
                      </small>
                    </td>
                    <td>
                      {% if record.issue_date %}
                        <span class="text-primary">{{ record.issue_date|date:"d.m.Y" }}</span>
                      {% else %}
                          <a class="link-secondary" href="{% url 'posts:record_add_issue' record.pk %}">
                            Не выдан  ✎
                          </a>
                      {% endif %}
                    </td>
                    <td>{{ record.recipient }}</td>
                    <td>
                        {% if not record.comment %}
                          <span class="text-body-secondary fw-lighter fst-italic">
                            Комменатрий отсуствует
                          </span>
                        {% else %}
                          {{ record.comment }}
                        {% endif %}
                    </td>
                    <td class="td-align">
                        <a type="button" class="btn btn-outline-dark" href="{% url 'posts:record_edit' record.pk %}">✎</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% include 'posts/includes/modal_post.html' %}

shtrixkod/templates/posts/index.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
 СУС «Штрих-код»
{% endblock %}
{% block content %}
<div class="container py-4">

  <div class="row">
    <div class="col">
      <a class="btn btn-primary btn-style" href="{% url 'posts:record_create' %}" role="button"> 
        Добавить запись
      </a>
      <a type="button" class="btn btn-style btn-primary" href="{% url 'posts:index' %}">Обновить таблицу</a>
    </div>
    <div class="col d-flex flex-row-reverse">
      {% comment %} <a type="button" class="btn btn-style btn-primary" href="{% url 'posts:index' %}">Обновить таблицу</a> {% endcomment %}
      <a class="btn btn-outline-primary {% if 'issue_date' in querydict.f %}active{% endif %}"  href="?f={% if 'issue_date' in querydict.f %}{{ querydict.f|checkoption:"issue_date" }}{% else %}issue_date{% endif %}">Отображать выданные позиции</a>
    </div>
  </div>

  <br>

  <div>
      <i>
        <font size="2">
          <span style="color: red;">*Красный - дата просрочена</span> |
          <span style="color: #ffaa00;">*Желтый - дата истекает</span> |
          <span style="color: green;">*Зеленый - дата актуальна</span> |
          <span style="color: #0d6efd;">*Синий - выдан со склада</span>
        </font>
      </i>
  </div>

  {% include 'posts/includes/table.html' %}

  <div class="d-flex flex-row-reverse">
      {% include 'posts/includes/paginator.html' %}
  </div>

  {% include 'posts/includes/modal_post.html' %}

</div>
{% endblock %}